[package]
name = "nomura2020"
version = "0.1.0"
authors = ["minami <minaminaoy@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"
algo = { git = "https://github.com/minaminao/algo-rs.git" }

[profile.release]
lto = true
panic = 'abort'
